#!/bin/sh

app_name=minestrone
data_dir=$HOME/data
volatile_dir=$HOME/volatile

dotcloud_get_env() {
    sed -n "/$1/ s/.*: \"\(.*\)\".*/\1/p" < "$HOME/environment.json"
}

setup_django() {
    # Create the data directories on the first push:
    if [ ! -d $data_dir/media ] || [ ! -d $volatile_dir/static ] ; then
        mkdir -p $data_dir/media $volatile_dir/static
    fi

    python $app_name/manage.py collectstatic --noinput

    python $app_name/manage.py syncdb --noinput
    python mkadmin.py
}

setup_django_celery() {
    cat > $HOME/current/supervisord.conf << EOF
[program:djcelery]
directory = $HOME/current/
command = python $app_name/manage.py celeryd -E -l info -c 2
stderr_logfile = /var/log/supervisor/%(program_name)s_error.log
stdout_logfile = /var/log/supervisor/%(program_name)s.log

[program:celerycam]
directory = $HOME/current/
command = python $app_name/manage.py celerycam
stderr_logfile = /var/log/supervisor/%(program_name)s_error.log
stdout_logfile = /var/log/supervisor/%(program_name)s.log
EOF
}

if [ `dotcloud_get_env SERVICE_NAME` = workers ] ; then
    setup_django_celery
else
    setup_django
fi
